[package]
name = "yupass"
version = "0.1.0"
authors = ["Isaac Mills <rooster0055@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpgme = "*"
bincode = "*"
serde = { version = "*", features = ["derive"] }
structopt = "*"
enigo = "*"
dirs = "*"
yubico_manager = "*"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
